version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    container_name: backend
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
