version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  demo-backend:
    container_name: demo-backend
    build:
      context: server
      dockerfile: Dockerfile
